doc-warnings: true
test-warnings: true
strictness: veryhigh
pep8:
  full: true
pylint:
  run: true
vulture:
  run: true
mccabe:
  run: true
max-line-length: 100
uses:
  - flask
autodetect: true
requirements:
  - requirements.txt
python-targets:
  - 3
