language: python
python:
  #  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

# save pip installs between runs
cache: "pip"

# services such as databases that can be used during tests
# services:
#   - memcached
#   - redis-server

# command to install dependencies
install: 
  - pip install -r requirements.txt

before_script:
  - ./lint.sh

script:
  - mypy --silent-imports app/
  - nosetests --with-timer --timer-top-n 5 --timer-ok 250ms --timer-warning 500ms --with-coverage --cover-erase --cover-html --cover-package=app --cover-branches
  - codecov
