language: python
python:
  #  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
#  - "nightly"

node_js:
  - "0.10"

# save pip installs between runs
cache: "pip"

# services such as databases that can be used during tests
services:
  - mongodb
#   - memcached
#   - redis-server

# command to install dependencies
install: 
  - pip install -r requirements.txt

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - ./lint.sh
  - npm install

script:
  - mypy --silent-imports --linecoverage-report mypycover --html-report mypycover --check-untyped-defs app/
  - nosetests --with-timer --timer-top-n 5 --timer-ok 250ms --timer-warning 500ms --with-coverage --cover-erase --cover-html --cover-package=app --cover-branches
  - codecov
  - node_modules/karma/bin/karma start my.conf.js --single-run